### ISSUE TITLE
Contenu protégé pour raison inconnue

### ISSUE THREAD

**Issue by ppodevin** [ze0/spoiler_protection#1]
Cet article :
![image](https://user-images.githubusercontent.com/12099945/58090641-f889ce80-7bc7-11e9-90ba-56779b768eba.png)
dont le lien est :
[netflix-amazon-ocs-canal-comparatif-plateformes-svod-streaming](https://www.journaldugeek.com/dossier/netflix-amazon-ocs-canal-comparatif-plateformes-svod-streaming/)
Qui semble être protégé par erreur.

**Comment by ze0** [comment]
c'est un article parlant d'ocs, utilisant une image de got spoilant l’importance d'un personnage pour la dernière saison.

est-ce vraiment une erreur ?

**Comment by ppodevin** [comment]
Je me demande bien comment le script fait pour remarquer la photo d'un perso GoT ;-)

**Comment by ze0** [comment]
Pour la postérité, le terme OCS est dans la liste actuellement, c'est pour ça
